import './globals.css'
import 'notyf/notyf.min.css'

export const metadata = {
  title: 'Hulu App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={` antialiased`}>{children}</body>
    </html>
  )
}
