import { NotfyProvider } from './context/NotfyProvider'
import './globals.css'

export const metadata = {
  title: 'Hulu App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <NotfyProvider>{children}</NotfyProvider>
      </body>
    </html>
  )
}
